#define 	    START	    1
#define 	    FUNC	    2
#define 	    VAR	        3
#define 	    CONST	    4
#define 	    IF	        5
#define 	    ELSE	    6
#define 	    WHILE	    7
#define 	    PRINT	    8
#define     	READ	    9
#define     	ID	        10
#define     	INTLITERAL  11
#define     	CADENA	    12
#define     	LPAREN	    13
#define     	RPAREN	    14
#define     	LBRACE	    15
#define     	RBRACE	    16
#define     	SEMICOLON   17
#define     	COMMA	    18
#define     	ASSIGNOP    19
#define     	PLUSOP	    20
#define     	MINUSOP	    21
#define     	MULTSOP	    22
#define     	DIVTSOP	    23
#define         CRAP        24